### ISSUE TITLE
UI and Editor

### ISSUE THREAD

**Issue by munael** [narfanar/b1-star#1]
- [ ] Chrome
  - [x] File bar/ribbon
  - [ ] Floating panels
  - [ ] .
- [ ] Design Inspiration Graph (DIG)
  - [ ] Viz
  - [ ] Visits-tracking edges
  - [ ] Branching
  - [ ] .
- [ ] Editor
  - [ ] Layers
  - [ ] Floating panels
  - [ ] .
